---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - secrets-manager.advok8s.io
  resources:
  - secretcopiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets-manager.advok8s.io
  resources:
  - secretcopiers/finalizers
  verbs:
  - update
- apiGroups:
  - secrets-manager.advok8s.io
  resources:
  - secretcopiers/status
  verbs:
  - get
  - patch
  - update
