---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - secrets.advok8s.io
  resources:
  - secretbuilders
  - secretcopiers
  - secretexporters
  - secretimporters
  - secretinjectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.advok8s.io
  resources:
  - secretbuilders/finalizers
  - secretcopiers/finalizers
  - secretexporters/finalizers
  - secretimporters/finalizers
  - secretinjectors/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.advok8s.io
  resources:
  - secretbuilders/status
  - secretcopiers/status
  - secretexporters/status
  - secretimporters/status
  - secretinjectors/status
  verbs:
  - get
  - patch
  - update
