# permissions for end users to edit secretcopiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: advok8s-secrets-manager
    app.kubernetes.io/managed-by: kustomize
  name: secretcopier-editor-role
rules:
- apiGroups:
  - secrets-manager.advok8s.io
  resources:
  - secretcopiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets-manager.advok8s.io
  resources:
  - secretcopiers/status
  verbs:
  - get
