//go:build !ignore_autogenerated

/*
Copyright 2024-2026 Graham Dumpleton.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	secretsv1beta1 "github.com/advok8s/advok8s-secrets-manager/api/secrets/v1beta1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapBuilder) DeepCopyInto(out *ConfigMapBuilder) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapBuilder.
func (in *ConfigMapBuilder) DeepCopy() *ConfigMapBuilder {
	if in == nil {
		return nil
	}
	out := new(ConfigMapBuilder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigMapBuilder) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapBuilderGenerator) DeepCopyInto(out *ConfigMapBuilderGenerator) {
	*out = *in
	if in.Script != nil {
		in, out := &in.Script, &out.Script
		*out = new(string)
		**out = **in
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(ConfigMapTemplateGenerator)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapBuilderGenerator.
func (in *ConfigMapBuilderGenerator) DeepCopy() *ConfigMapBuilderGenerator {
	if in == nil {
		return nil
	}
	out := new(ConfigMapBuilderGenerator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapBuilderInputs) DeepCopyInto(out *ConfigMapBuilderInputs) {
	*out = *in
	if in.Constants != nil {
		in, out := &in.Constants, &out.Constants
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]secretsv1beta1.SecretInput, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = make([]secretsv1beta1.ConfigMapInput, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Generated != nil {
		in, out := &in.Generated, &out.Generated
		*out = make([]ConfigMapGeneratedValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Libraries != nil {
		in, out := &in.Libraries, &out.Libraries
		*out = make([]secretsv1beta1.LibraryReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapBuilderInputs.
func (in *ConfigMapBuilderInputs) DeepCopy() *ConfigMapBuilderInputs {
	if in == nil {
		return nil
	}
	out := new(ConfigMapBuilderInputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapBuilderList) DeepCopyInto(out *ConfigMapBuilderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigMapBuilder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapBuilderList.
func (in *ConfigMapBuilderList) DeepCopy() *ConfigMapBuilderList {
	if in == nil {
		return nil
	}
	out := new(ConfigMapBuilderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigMapBuilderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapBuilderOutput) DeepCopyInto(out *ConfigMapBuilderOutput) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapBuilderOutput.
func (in *ConfigMapBuilderOutput) DeepCopy() *ConfigMapBuilderOutput {
	if in == nil {
		return nil
	}
	out := new(ConfigMapBuilderOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapBuilderSpec) DeepCopyInto(out *ConfigMapBuilderSpec) {
	*out = *in
	in.Inputs.DeepCopyInto(&out.Inputs)
	in.Output.DeepCopyInto(&out.Output)
	in.Generator.DeepCopyInto(&out.Generator)
	in.Regeneration.DeepCopyInto(&out.Regeneration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapBuilderSpec.
func (in *ConfigMapBuilderSpec) DeepCopy() *ConfigMapBuilderSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigMapBuilderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapBuilderStatus) DeepCopyInto(out *ConfigMapBuilderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastGeneratedTime != nil {
		in, out := &in.LastGeneratedTime, &out.LastGeneratedTime
		*out = (*in).DeepCopy()
	}
	if in.NextRotationTime != nil {
		in, out := &in.NextRotationTime, &out.NextRotationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapBuilderStatus.
func (in *ConfigMapBuilderStatus) DeepCopy() *ConfigMapBuilderStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigMapBuilderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapCopier) DeepCopyInto(out *ConfigMapCopier) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapCopier.
func (in *ConfigMapCopier) DeepCopy() *ConfigMapCopier {
	if in == nil {
		return nil
	}
	out := new(ConfigMapCopier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigMapCopier) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapCopierList) DeepCopyInto(out *ConfigMapCopierList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigMapCopier, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapCopierList.
func (in *ConfigMapCopierList) DeepCopy() *ConfigMapCopierList {
	if in == nil {
		return nil
	}
	out := new(ConfigMapCopierList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigMapCopierList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapCopierRule) DeepCopyInto(out *ConfigMapCopierRule) {
	*out = *in
	out.SourceConfigMap = in.SourceConfigMap
	in.TargetNamespaces.DeepCopyInto(&out.TargetNamespaces)
	in.TargetConfigMap.DeepCopyInto(&out.TargetConfigMap)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapCopierRule.
func (in *ConfigMapCopierRule) DeepCopy() *ConfigMapCopierRule {
	if in == nil {
		return nil
	}
	out := new(ConfigMapCopierRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapCopierSpec) DeepCopyInto(out *ConfigMapCopierSpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]ConfigMapCopierRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapCopierSpec.
func (in *ConfigMapCopierSpec) DeepCopy() *ConfigMapCopierSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigMapCopierSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapCopierStatus) DeepCopyInto(out *ConfigMapCopierStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Summary = in.Summary
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]ConfigMapRuleStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapCopierStatus.
func (in *ConfigMapCopierStatus) DeepCopy() *ConfigMapCopierStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigMapCopierStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapCopierSummary) DeepCopyInto(out *ConfigMapCopierSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapCopierSummary.
func (in *ConfigMapCopierSummary) DeepCopy() *ConfigMapCopierSummary {
	if in == nil {
		return nil
	}
	out := new(ConfigMapCopierSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapGeneratedValue) DeepCopyInto(out *ConfigMapGeneratedValue) {
	*out = *in
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(secretsv1beta1.UUIDSpec)
		**out = **in
	}
	if in.RandomInt != nil {
		in, out := &in.RandomInt, &out.RandomInt
		*out = new(secretsv1beta1.RandomIntSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapGeneratedValue.
func (in *ConfigMapGeneratedValue) DeepCopy() *ConfigMapGeneratedValue {
	if in == nil {
		return nil
	}
	out := new(ConfigMapGeneratedValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapRuleStatus) DeepCopyInto(out *ConfigMapRuleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapRuleStatus.
func (in *ConfigMapRuleStatus) DeepCopy() *ConfigMapRuleStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigMapRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapTemplateGenerator) DeepCopyInto(out *ConfigMapTemplateGenerator) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapTemplateGenerator.
func (in *ConfigMapTemplateGenerator) DeepCopy() *ConfigMapTemplateGenerator {
	if in == nil {
		return nil
	}
	out := new(ConfigMapTemplateGenerator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceConfigMap) DeepCopyInto(out *SourceConfigMap) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceConfigMap.
func (in *SourceConfigMap) DeepCopy() *SourceConfigMap {
	if in == nil {
		return nil
	}
	out := new(SourceConfigMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetConfigMap) DeepCopyInto(out *TargetConfigMap) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetConfigMap.
func (in *TargetConfigMap) DeepCopy() *TargetConfigMap {
	if in == nil {
		return nil
	}
	out := new(TargetConfigMap)
	in.DeepCopyInto(out)
	return out
}
