apiVersion: configmaps.advok8s.io/v1beta1
kind: ConfigMapBuilder
metadata:
  labels:
    app.kubernetes.io/name: advok8s-secrets-manager
    app.kubernetes.io/managed-by: kustomize
  name: configmapbuilder-sample
spec:
  inputs:
    constants:
      environment: production
    generated:
    - name: instance
      uuid: {}
  generator:
    script: |
      configMap = {
          "data": {
              "environment": input.constants.environment,
              "instanceId": input.generated.instance.value,
          },
          "labels": {"app": "demo"},
      }
