## Append samples of your project ##
resources:
- secrets_v1beta1_secretcopier.yaml
- secrets_v1beta1_secretexporter.yaml
- secrets_v1beta1_secretimporter.yaml
- secrets_v1beta1_secretinjector.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
