apiVersion: secrets.advok8s.io/v1beta1
kind: SecretCopier
metadata:
  labels:
    app.kubernetes.io/name: advok8s-secrets-manager
    app.kubernetes.io/managed-by: kustomize
  name: secretcopier-sample
spec:
  # TODO(user): Add fields here
