apiVersion: secrets.advok8s.io/v1beta1
kind: SecretCopier
metadata:
  labels:
    app.kubernetes.io/name: advok8s-secrets-manager
    app.kubernetes.io/managed-by: kustomize
  name: secretcopier-sample
spec:
  rules:
  - sourceSecret:
      name: secret-1
      namespace: source-namespace-1
    targetNamespaces:
      nameSelector:
        matchNames:
        - target-namespace-1
        - target-namespace-2
