//go:build !ignore_autogenerated

/*
Copyright 2024 Graham Dumpleton.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCopier) DeepCopyInto(out *SecretCopier) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCopier.
func (in *SecretCopier) DeepCopy() *SecretCopier {
	if in == nil {
		return nil
	}
	out := new(SecretCopier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretCopier) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCopierList) DeepCopyInto(out *SecretCopierList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretCopier, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCopierList.
func (in *SecretCopierList) DeepCopy() *SecretCopierList {
	if in == nil {
		return nil
	}
	out := new(SecretCopierList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretCopierList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCopierRule) DeepCopyInto(out *SecretCopierRule) {
	*out = *in
	out.SourceSecret = in.SourceSecret
	in.TargetNamespaces.DeepCopyInto(&out.TargetNamespaces)
	in.TargetSecret.DeepCopyInto(&out.TargetSecret)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCopierRule.
func (in *SecretCopierRule) DeepCopy() *SecretCopierRule {
	if in == nil {
		return nil
	}
	out := new(SecretCopierRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCopierSpec) DeepCopyInto(out *SecretCopierSpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]SecretCopierRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.SyncPeriod = in.SyncPeriod
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCopierSpec.
func (in *SecretCopierSpec) DeepCopy() *SecretCopierSpec {
	if in == nil {
		return nil
	}
	out := new(SecretCopierSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCopierStatus) DeepCopyInto(out *SecretCopierStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCopierStatus.
func (in *SecretCopierStatus) DeepCopy() *SecretCopierStatus {
	if in == nil {
		return nil
	}
	out := new(SecretCopierStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSecret) DeepCopyInto(out *SourceSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSecret.
func (in *SourceSecret) DeepCopy() *SourceSecret {
	if in == nil {
		return nil
	}
	out := new(SourceSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSecret) DeepCopyInto(out *TargetSecret) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSecret.
func (in *TargetSecret) DeepCopy() *TargetSecret {
	if in == nil {
		return nil
	}
	out := new(TargetSecret)
	in.DeepCopyInto(out)
	return out
}
