//go:build !ignore_autogenerated

/*
Copyright 2024-2026 Graham Dumpleton.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopyAuthorization) DeepCopyInto(out *CopyAuthorization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopyAuthorization.
func (in *CopyAuthorization) DeepCopy() *CopyAuthorization {
	if in == nil {
		return nil
	}
	out := new(CopyAuthorization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImporterSourceNamespaces) DeepCopyInto(out *ImporterSourceNamespaces) {
	*out = *in
	in.NameSelector.DeepCopyInto(&out.NameSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImporterSourceNamespaces.
func (in *ImporterSourceNamespaces) DeepCopy() *ImporterSourceNamespaces {
	if in == nil {
		return nil
	}
	out := new(ImporterSourceNamespaces)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleStatus) DeepCopyInto(out *RuleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleStatus.
func (in *RuleStatus) DeepCopy() *RuleStatus {
	if in == nil {
		return nil
	}
	out := new(RuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCopier) DeepCopyInto(out *SecretCopier) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCopier.
func (in *SecretCopier) DeepCopy() *SecretCopier {
	if in == nil {
		return nil
	}
	out := new(SecretCopier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretCopier) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCopierList) DeepCopyInto(out *SecretCopierList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretCopier, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCopierList.
func (in *SecretCopierList) DeepCopy() *SecretCopierList {
	if in == nil {
		return nil
	}
	out := new(SecretCopierList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretCopierList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCopierRule) DeepCopyInto(out *SecretCopierRule) {
	*out = *in
	out.SourceSecret = in.SourceSecret
	in.TargetNamespaces.DeepCopyInto(&out.TargetNamespaces)
	in.TargetSecret.DeepCopyInto(&out.TargetSecret)
	out.CopyAuthorization = in.CopyAuthorization
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCopierRule.
func (in *SecretCopierRule) DeepCopy() *SecretCopierRule {
	if in == nil {
		return nil
	}
	out := new(SecretCopierRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCopierSpec) DeepCopyInto(out *SecretCopierSpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]SecretCopierRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SyncPeriod != nil {
		in, out := &in.SyncPeriod, &out.SyncPeriod
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCopierSpec.
func (in *SecretCopierSpec) DeepCopy() *SecretCopierSpec {
	if in == nil {
		return nil
	}
	out := new(SecretCopierSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCopierStatus) DeepCopyInto(out *SecretCopierStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Summary = in.Summary
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]RuleStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCopierStatus.
func (in *SecretCopierStatus) DeepCopy() *SecretCopierStatus {
	if in == nil {
		return nil
	}
	out := new(SecretCopierStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCopierSummary) DeepCopyInto(out *SecretCopierSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCopierSummary.
func (in *SecretCopierSummary) DeepCopy() *SecretCopierSummary {
	if in == nil {
		return nil
	}
	out := new(SecretCopierSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretExporter) DeepCopyInto(out *SecretExporter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretExporter.
func (in *SecretExporter) DeepCopy() *SecretExporter {
	if in == nil {
		return nil
	}
	out := new(SecretExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretExporter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretExporterCounts) DeepCopyInto(out *SecretExporterCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretExporterCounts.
func (in *SecretExporterCounts) DeepCopy() *SecretExporterCounts {
	if in == nil {
		return nil
	}
	out := new(SecretExporterCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretExporterList) DeepCopyInto(out *SecretExporterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretExporter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretExporterList.
func (in *SecretExporterList) DeepCopy() *SecretExporterList {
	if in == nil {
		return nil
	}
	out := new(SecretExporterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretExporterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretExporterRule) DeepCopyInto(out *SecretExporterRule) {
	*out = *in
	in.TargetNamespaces.DeepCopyInto(&out.TargetNamespaces)
	in.TargetSecret.DeepCopyInto(&out.TargetSecret)
	out.CopyAuthorization = in.CopyAuthorization
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretExporterRule.
func (in *SecretExporterRule) DeepCopy() *SecretExporterRule {
	if in == nil {
		return nil
	}
	out := new(SecretExporterRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretExporterSpec) DeepCopyInto(out *SecretExporterSpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]SecretExporterRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SyncPeriod != nil {
		in, out := &in.SyncPeriod, &out.SyncPeriod
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretExporterSpec.
func (in *SecretExporterSpec) DeepCopy() *SecretExporterSpec {
	if in == nil {
		return nil
	}
	out := new(SecretExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretExporterStatus) DeepCopyInto(out *SecretExporterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Summary = in.Summary
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]SecretExporterCounts, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretExporterStatus.
func (in *SecretExporterStatus) DeepCopy() *SecretExporterStatus {
	if in == nil {
		return nil
	}
	out := new(SecretExporterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretImporter) DeepCopyInto(out *SecretImporter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretImporter.
func (in *SecretImporter) DeepCopy() *SecretImporter {
	if in == nil {
		return nil
	}
	out := new(SecretImporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretImporter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretImporterList) DeepCopyInto(out *SecretImporterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretImporter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretImporterList.
func (in *SecretImporterList) DeepCopy() *SecretImporterList {
	if in == nil {
		return nil
	}
	out := new(SecretImporterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretImporterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretImporterSpec) DeepCopyInto(out *SecretImporterSpec) {
	*out = *in
	if in.SourceNamespaces != nil {
		in, out := &in.SourceNamespaces, &out.SourceNamespaces
		*out = new(ImporterSourceNamespaces)
		(*in).DeepCopyInto(*out)
	}
	out.CopyAuthorization = in.CopyAuthorization
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretImporterSpec.
func (in *SecretImporterSpec) DeepCopy() *SecretImporterSpec {
	if in == nil {
		return nil
	}
	out := new(SecretImporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretImporterStatus) DeepCopyInto(out *SecretImporterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretImporterStatus.
func (in *SecretImporterStatus) DeepCopy() *SecretImporterStatus {
	if in == nil {
		return nil
	}
	out := new(SecretImporterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSecret) DeepCopyInto(out *SourceSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSecret.
func (in *SourceSecret) DeepCopy() *SourceSecret {
	if in == nil {
		return nil
	}
	out := new(SourceSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSecret) DeepCopyInto(out *TargetSecret) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSecret.
func (in *TargetSecret) DeepCopy() *TargetSecret {
	if in == nil {
		return nil
	}
	out := new(TargetSecret)
	in.DeepCopyInto(out)
	return out
}
