//go:build !ignore_autogenerated

/*
Copyright 2024-2026 Graham Dumpleton.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/advok8s/advok8s-secrets-manager/pkg/selectors"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BytesSpec) DeepCopyInto(out *BytesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BytesSpec.
func (in *BytesSpec) DeepCopy() *BytesSpec {
	if in == nil {
		return nil
	}
	out := new(BytesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CACertificateSpec) DeepCopyInto(out *CACertificateSpec) {
	*out = *in
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(CertificateSubject)
		(*in).DeepCopyInto(*out)
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.IssuerRef != nil {
		in, out := &in.IssuerRef, &out.IssuerRef
		*out = new(IssuerReference)
		**out = **in
	}
	if in.MaxPathLen != nil {
		in, out := &in.MaxPathLen, &out.MaxPathLen
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CACertificateSpec.
func (in *CACertificateSpec) DeepCopy() *CACertificateSpec {
	if in == nil {
		return nil
	}
	out := new(CACertificateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSubject) DeepCopyInto(out *CertificateSubject) {
	*out = *in
	if in.Organizations != nil {
		in, out := &in.Organizations, &out.Organizations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OrganizationalUnits != nil {
		in, out := &in.OrganizationalUnits, &out.OrganizationalUnits
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Countries != nil {
		in, out := &in.Countries, &out.Countries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Localities != nil {
		in, out := &in.Localities, &out.Localities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Provinces != nil {
		in, out := &in.Provinces, &out.Provinces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostalCodes != nil {
		in, out := &in.PostalCodes, &out.PostalCodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSubject.
func (in *CertificateSubject) DeepCopy() *CertificateSubject {
	if in == nil {
		return nil
	}
	out := new(CertificateSubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapInput) DeepCopyInto(out *ConfigMapInput) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(selectors.SecretSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapInput.
func (in *ConfigMapInput) DeepCopy() *ConfigMapInput {
	if in == nil {
		return nil
	}
	out := new(ConfigMapInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopyAuthorization) DeepCopyInto(out *CopyAuthorization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopyAuthorization.
func (in *CopyAuthorization) DeepCopy() *CopyAuthorization {
	if in == nil {
		return nil
	}
	out := new(CopyAuthorization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ECDSAPrivateKeySpec) DeepCopyInto(out *ECDSAPrivateKeySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ECDSAPrivateKeySpec.
func (in *ECDSAPrivateKeySpec) DeepCopy() *ECDSAPrivateKeySpec {
	if in == nil {
		return nil
	}
	out := new(ECDSAPrivateKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratedValue) DeepCopyInto(out *GeneratedValue) {
	*out = *in
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(PasswordSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(TokenSpec)
		**out = **in
	}
	if in.RandomInt != nil {
		in, out := &in.RandomInt, &out.RandomInt
		*out = new(RandomIntSpec)
		**out = **in
	}
	if in.Bytes != nil {
		in, out := &in.Bytes, &out.Bytes
		*out = new(BytesSpec)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(UUIDSpec)
		**out = **in
	}
	if in.RSAPrivateKey != nil {
		in, out := &in.RSAPrivateKey, &out.RSAPrivateKey
		*out = new(RSAPrivateKeySpec)
		**out = **in
	}
	if in.ECDSAPrivateKey != nil {
		in, out := &in.ECDSAPrivateKey, &out.ECDSAPrivateKey
		*out = new(ECDSAPrivateKeySpec)
		**out = **in
	}
	if in.SSHKeyPair != nil {
		in, out := &in.SSHKeyPair, &out.SSHKeyPair
		*out = new(SSHKeyPairSpec)
		**out = **in
	}
	if in.CACertificate != nil {
		in, out := &in.CACertificate, &out.CACertificate
		*out = new(CACertificateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TLSCertificate != nil {
		in, out := &in.TLSCertificate, &out.TLSCertificate
		*out = new(TLSCertificateSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratedValue.
func (in *GeneratedValue) DeepCopy() *GeneratedValue {
	if in == nil {
		return nil
	}
	out := new(GeneratedValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImporterSourceNamespaces) DeepCopyInto(out *ImporterSourceNamespaces) {
	*out = *in
	in.NameSelector.DeepCopyInto(&out.NameSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImporterSourceNamespaces.
func (in *ImporterSourceNamespaces) DeepCopy() *ImporterSourceNamespaces {
	if in == nil {
		return nil
	}
	out := new(ImporterSourceNamespaces)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssuerReference) DeepCopyInto(out *IssuerReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssuerReference.
func (in *IssuerReference) DeepCopy() *IssuerReference {
	if in == nil {
		return nil
	}
	out := new(IssuerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LibraryReference) DeepCopyInto(out *LibraryReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LibraryReference.
func (in *LibraryReference) DeepCopy() *LibraryReference {
	if in == nil {
		return nil
	}
	out := new(LibraryReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PasswordSpec) DeepCopyInto(out *PasswordSpec) {
	*out = *in
	if in.Upper != nil {
		in, out := &in.Upper, &out.Upper
		*out = new(bool)
		**out = **in
	}
	if in.Lower != nil {
		in, out := &in.Lower, &out.Lower
		*out = new(bool)
		**out = **in
	}
	if in.Digits != nil {
		in, out := &in.Digits, &out.Digits
		*out = new(bool)
		**out = **in
	}
	if in.Symbols != nil {
		in, out := &in.Symbols, &out.Symbols
		*out = new(bool)
		**out = **in
	}
	if in.AllowRepeat != nil {
		in, out := &in.AllowRepeat, &out.AllowRepeat
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PasswordSpec.
func (in *PasswordSpec) DeepCopy() *PasswordSpec {
	if in == nil {
		return nil
	}
	out := new(PasswordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RSAPrivateKeySpec) DeepCopyInto(out *RSAPrivateKeySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RSAPrivateKeySpec.
func (in *RSAPrivateKeySpec) DeepCopy() *RSAPrivateKeySpec {
	if in == nil {
		return nil
	}
	out := new(RSAPrivateKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RandomIntSpec) DeepCopyInto(out *RandomIntSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RandomIntSpec.
func (in *RandomIntSpec) DeepCopy() *RandomIntSpec {
	if in == nil {
		return nil
	}
	out := new(RandomIntSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Regeneration) DeepCopyInto(out *Regeneration) {
	*out = *in
	if in.RotateEvery != nil {
		in, out := &in.RotateEvery, &out.RotateEvery
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Regeneration.
func (in *Regeneration) DeepCopy() *Regeneration {
	if in == nil {
		return nil
	}
	out := new(Regeneration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleStatus) DeepCopyInto(out *RuleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleStatus.
func (in *RuleStatus) DeepCopy() *RuleStatus {
	if in == nil {
		return nil
	}
	out := new(RuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHKeyPairSpec) DeepCopyInto(out *SSHKeyPairSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHKeyPairSpec.
func (in *SSHKeyPairSpec) DeepCopy() *SSHKeyPairSpec {
	if in == nil {
		return nil
	}
	out := new(SSHKeyPairSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretBuilder) DeepCopyInto(out *SecretBuilder) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretBuilder.
func (in *SecretBuilder) DeepCopy() *SecretBuilder {
	if in == nil {
		return nil
	}
	out := new(SecretBuilder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretBuilder) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretBuilderGenerator) DeepCopyInto(out *SecretBuilderGenerator) {
	*out = *in
	if in.Script != nil {
		in, out := &in.Script, &out.Script
		*out = new(string)
		**out = **in
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(TemplateGenerator)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretBuilderGenerator.
func (in *SecretBuilderGenerator) DeepCopy() *SecretBuilderGenerator {
	if in == nil {
		return nil
	}
	out := new(SecretBuilderGenerator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretBuilderInputs) DeepCopyInto(out *SecretBuilderInputs) {
	*out = *in
	if in.Constants != nil {
		in, out := &in.Constants, &out.Constants
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]SecretInput, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = make([]ConfigMapInput, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(ServiceAccountInput)
		(*in).DeepCopyInto(*out)
	}
	if in.Generated != nil {
		in, out := &in.Generated, &out.Generated
		*out = make([]GeneratedValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Libraries != nil {
		in, out := &in.Libraries, &out.Libraries
		*out = make([]LibraryReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretBuilderInputs.
func (in *SecretBuilderInputs) DeepCopy() *SecretBuilderInputs {
	if in == nil {
		return nil
	}
	out := new(SecretBuilderInputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretBuilderList) DeepCopyInto(out *SecretBuilderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretBuilder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretBuilderList.
func (in *SecretBuilderList) DeepCopy() *SecretBuilderList {
	if in == nil {
		return nil
	}
	out := new(SecretBuilderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretBuilderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretBuilderOutput) DeepCopyInto(out *SecretBuilderOutput) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretBuilderOutput.
func (in *SecretBuilderOutput) DeepCopy() *SecretBuilderOutput {
	if in == nil {
		return nil
	}
	out := new(SecretBuilderOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretBuilderSpec) DeepCopyInto(out *SecretBuilderSpec) {
	*out = *in
	in.Inputs.DeepCopyInto(&out.Inputs)
	in.Output.DeepCopyInto(&out.Output)
	in.Generator.DeepCopyInto(&out.Generator)
	in.Regeneration.DeepCopyInto(&out.Regeneration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretBuilderSpec.
func (in *SecretBuilderSpec) DeepCopy() *SecretBuilderSpec {
	if in == nil {
		return nil
	}
	out := new(SecretBuilderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretBuilderStatus) DeepCopyInto(out *SecretBuilderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastGeneratedTime != nil {
		in, out := &in.LastGeneratedTime, &out.LastGeneratedTime
		*out = (*in).DeepCopy()
	}
	if in.NextRotationTime != nil {
		in, out := &in.NextRotationTime, &out.NextRotationTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretBuilderStatus.
func (in *SecretBuilderStatus) DeepCopy() *SecretBuilderStatus {
	if in == nil {
		return nil
	}
	out := new(SecretBuilderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCopier) DeepCopyInto(out *SecretCopier) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCopier.
func (in *SecretCopier) DeepCopy() *SecretCopier {
	if in == nil {
		return nil
	}
	out := new(SecretCopier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretCopier) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCopierList) DeepCopyInto(out *SecretCopierList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretCopier, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCopierList.
func (in *SecretCopierList) DeepCopy() *SecretCopierList {
	if in == nil {
		return nil
	}
	out := new(SecretCopierList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretCopierList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCopierRule) DeepCopyInto(out *SecretCopierRule) {
	*out = *in
	out.SourceSecret = in.SourceSecret
	in.TargetNamespaces.DeepCopyInto(&out.TargetNamespaces)
	in.TargetSecret.DeepCopyInto(&out.TargetSecret)
	out.CopyAuthorization = in.CopyAuthorization
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCopierRule.
func (in *SecretCopierRule) DeepCopy() *SecretCopierRule {
	if in == nil {
		return nil
	}
	out := new(SecretCopierRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCopierSpec) DeepCopyInto(out *SecretCopierSpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]SecretCopierRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCopierSpec.
func (in *SecretCopierSpec) DeepCopy() *SecretCopierSpec {
	if in == nil {
		return nil
	}
	out := new(SecretCopierSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCopierStatus) DeepCopyInto(out *SecretCopierStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Summary = in.Summary
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]RuleStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCopierStatus.
func (in *SecretCopierStatus) DeepCopy() *SecretCopierStatus {
	if in == nil {
		return nil
	}
	out := new(SecretCopierStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretCopierSummary) DeepCopyInto(out *SecretCopierSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretCopierSummary.
func (in *SecretCopierSummary) DeepCopy() *SecretCopierSummary {
	if in == nil {
		return nil
	}
	out := new(SecretCopierSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretExporter) DeepCopyInto(out *SecretExporter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretExporter.
func (in *SecretExporter) DeepCopy() *SecretExporter {
	if in == nil {
		return nil
	}
	out := new(SecretExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretExporter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretExporterCounts) DeepCopyInto(out *SecretExporterCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretExporterCounts.
func (in *SecretExporterCounts) DeepCopy() *SecretExporterCounts {
	if in == nil {
		return nil
	}
	out := new(SecretExporterCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretExporterList) DeepCopyInto(out *SecretExporterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretExporter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretExporterList.
func (in *SecretExporterList) DeepCopy() *SecretExporterList {
	if in == nil {
		return nil
	}
	out := new(SecretExporterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretExporterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretExporterRule) DeepCopyInto(out *SecretExporterRule) {
	*out = *in
	in.TargetNamespaces.DeepCopyInto(&out.TargetNamespaces)
	in.TargetSecret.DeepCopyInto(&out.TargetSecret)
	out.CopyAuthorization = in.CopyAuthorization
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretExporterRule.
func (in *SecretExporterRule) DeepCopy() *SecretExporterRule {
	if in == nil {
		return nil
	}
	out := new(SecretExporterRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretExporterSpec) DeepCopyInto(out *SecretExporterSpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]SecretExporterRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretExporterSpec.
func (in *SecretExporterSpec) DeepCopy() *SecretExporterSpec {
	if in == nil {
		return nil
	}
	out := new(SecretExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretExporterStatus) DeepCopyInto(out *SecretExporterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Summary = in.Summary
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]SecretExporterCounts, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretExporterStatus.
func (in *SecretExporterStatus) DeepCopy() *SecretExporterStatus {
	if in == nil {
		return nil
	}
	out := new(SecretExporterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretImporter) DeepCopyInto(out *SecretImporter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretImporter.
func (in *SecretImporter) DeepCopy() *SecretImporter {
	if in == nil {
		return nil
	}
	out := new(SecretImporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretImporter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretImporterList) DeepCopyInto(out *SecretImporterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretImporter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretImporterList.
func (in *SecretImporterList) DeepCopy() *SecretImporterList {
	if in == nil {
		return nil
	}
	out := new(SecretImporterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretImporterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretImporterSpec) DeepCopyInto(out *SecretImporterSpec) {
	*out = *in
	if in.SourceNamespaces != nil {
		in, out := &in.SourceNamespaces, &out.SourceNamespaces
		*out = new(ImporterSourceNamespaces)
		(*in).DeepCopyInto(*out)
	}
	out.CopyAuthorization = in.CopyAuthorization
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretImporterSpec.
func (in *SecretImporterSpec) DeepCopy() *SecretImporterSpec {
	if in == nil {
		return nil
	}
	out := new(SecretImporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretImporterStatus) DeepCopyInto(out *SecretImporterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretImporterStatus.
func (in *SecretImporterStatus) DeepCopy() *SecretImporterStatus {
	if in == nil {
		return nil
	}
	out := new(SecretImporterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretInjector) DeepCopyInto(out *SecretInjector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretInjector.
func (in *SecretInjector) DeepCopy() *SecretInjector {
	if in == nil {
		return nil
	}
	out := new(SecretInjector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretInjector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretInjectorCounts) DeepCopyInto(out *SecretInjectorCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretInjectorCounts.
func (in *SecretInjectorCounts) DeepCopy() *SecretInjectorCounts {
	if in == nil {
		return nil
	}
	out := new(SecretInjectorCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretInjectorList) DeepCopyInto(out *SecretInjectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretInjector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretInjectorList.
func (in *SecretInjectorList) DeepCopy() *SecretInjectorList {
	if in == nil {
		return nil
	}
	out := new(SecretInjectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretInjectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretInjectorRule) DeepCopyInto(out *SecretInjectorRule) {
	*out = *in
	in.SourceSecrets.DeepCopyInto(&out.SourceSecrets)
	in.TargetNamespaces.DeepCopyInto(&out.TargetNamespaces)
	in.ServiceAccounts.DeepCopyInto(&out.ServiceAccounts)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretInjectorRule.
func (in *SecretInjectorRule) DeepCopy() *SecretInjectorRule {
	if in == nil {
		return nil
	}
	out := new(SecretInjectorRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretInjectorSpec) DeepCopyInto(out *SecretInjectorSpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]SecretInjectorRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretInjectorSpec.
func (in *SecretInjectorSpec) DeepCopy() *SecretInjectorSpec {
	if in == nil {
		return nil
	}
	out := new(SecretInjectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretInjectorStatus) DeepCopyInto(out *SecretInjectorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Summary = in.Summary
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]SecretInjectorCounts, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretInjectorStatus.
func (in *SecretInjectorStatus) DeepCopy() *SecretInjectorStatus {
	if in == nil {
		return nil
	}
	out := new(SecretInjectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretInput) DeepCopyInto(out *SecretInput) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(selectors.SecretSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretInput.
func (in *SecretInput) DeepCopy() *SecretInput {
	if in == nil {
		return nil
	}
	out := new(SecretInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountInput) DeepCopyInto(out *ServiceAccountInput) {
	*out = *in
	out.ServiceAccountRef = in.ServiceAccountRef
	if in.Audiences != nil {
		in, out := &in.Audiences, &out.Audiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExpirationSeconds != nil {
		in, out := &in.ExpirationSeconds, &out.ExpirationSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountInput.
func (in *ServiceAccountInput) DeepCopy() *ServiceAccountInput {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSecret) DeepCopyInto(out *SourceSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSecret.
func (in *SourceSecret) DeepCopy() *SourceSecret {
	if in == nil {
		return nil
	}
	out := new(SourceSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSCertificateSpec) DeepCopyInto(out *TLSCertificateSpec) {
	*out = *in
	if in.Subject != nil {
		in, out := &in.Subject, &out.Subject
		*out = new(CertificateSubject)
		(*in).DeepCopyInto(*out)
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.IssuerRef != nil {
		in, out := &in.IssuerRef, &out.IssuerRef
		*out = new(IssuerReference)
		**out = **in
	}
	if in.DNSNames != nil {
		in, out := &in.DNSNames, &out.DNSNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IPAddresses != nil {
		in, out := &in.IPAddresses, &out.IPAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.URIs != nil {
		in, out := &in.URIs, &out.URIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EmailAddresses != nil {
		in, out := &in.EmailAddresses, &out.EmailAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Usages != nil {
		in, out := &in.Usages, &out.Usages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSCertificateSpec.
func (in *TLSCertificateSpec) DeepCopy() *TLSCertificateSpec {
	if in == nil {
		return nil
	}
	out := new(TLSCertificateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSecret) DeepCopyInto(out *TargetSecret) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSecret.
func (in *TargetSecret) DeepCopy() *TargetSecret {
	if in == nil {
		return nil
	}
	out := new(TargetSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateGenerator) DeepCopyInto(out *TemplateGenerator) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateGenerator.
func (in *TemplateGenerator) DeepCopy() *TemplateGenerator {
	if in == nil {
		return nil
	}
	out := new(TemplateGenerator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenSpec) DeepCopyInto(out *TokenSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenSpec.
func (in *TokenSpec) DeepCopy() *TokenSpec {
	if in == nil {
		return nil
	}
	out := new(TokenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UUIDSpec) DeepCopyInto(out *UUIDSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UUIDSpec.
func (in *UUIDSpec) DeepCopy() *UUIDSpec {
	if in == nil {
		return nil
	}
	out := new(UUIDSpec)
	in.DeepCopyInto(out)
	return out
}
